apiVersion: v1
kind: Secret
metadata:
  name: greeting-secret
  labels:
    app: greeting-service
type: Opaque
data:
  application.yml: c2VjcmV0OgogIHBhc3N3b3JkOiBzZWNyZXQtcGFzc3dvcmQ=


#encoded string:
#secret:
#  password: secret-password
#decode string:
#  c2VjcmV0OgogIHBhc3N3b3JkOiBzZWNyZXQtcGFzc3dvcmQ=
